-- MySQL Script generated by MySQL Workbench
-- Wed Sep 23 14:34:01 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurantes_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantes_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantes_db` ;
USE `restaurantes_db` ;

-- -----------------------------------------------------
-- Table `restaurantes_db`.`TIPO_RES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`TIPO_RES` (
  `TIP_RES_COD` INT NOT NULL,
  `TIP_RES_CLASS` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIP_RES_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`TIPO_PRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`TIPO_PRATO` (
  `TIP_PRA_COD` INT NOT NULL,
  `TIP_PRA_NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`TIP_PRA_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`FORMA_PAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`FORMA_PAG` (
  `FOR_PAG_COD` INT NOT NULL,
  `FOR_PAG_NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`FOR_PAG_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`RETIRADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`RETIRADA` (
  `RET_COD` INT NOT NULL,
  `RET_NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`RET_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`RESTAURANTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`RESTAURANTES` (
  `RES_CNPJ` CHAR(14) NOT NULL,
  `RES_NOME` CHAR(60) NOT NULL,
  `RES_EMAIL` CHAR(60) NOT NULL,
  `RES_CONTATO` CHAR(11) NOT NULL,
  `RES_LOGRADOURO` VARCHAR(45) NOT NULL,
  `RES_BAIRRO` CHAR(35) NOT NULL,
  `RES_CIDADE` CHAR(35) NOT NULL,
  `RES_UF` CHAR(2) NOT NULL,
  `RES_CEP` CHAR(8) NOT NULL,
  `RES_SENHA` VARCHAR(100) NOT NULL,
  `TIP_RES_COD` INT NOT NULL,
  PRIMARY KEY (`RES_CNPJ`),
  INDEX `FK_RES_TIPRES` (`TIP_RES_COD` ASC) VISIBLE,
  UNIQUE INDEX `RES_CNPJ_UNIQUE` (`RES_CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `RES_EMAIL_UNIQUE` (`RES_EMAIL` ASC) VISIBLE,
  CONSTRAINT `FK_RES_TIPRES`
    FOREIGN KEY (`TIP_RES_COD`)
    REFERENCES `restaurantes_db`.`TIPO_RES` (`TIP_RES_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`CLIENTES` (
  `CLI_CPF` CHAR(11) NOT NULL,
  `CLI_NOME` VARCHAR(100) NOT NULL,
  `CLI_EMAIL` VARCHAR(100) NOT NULL,
  `CLI_DATA_NAS` DATE NOT NULL,
  `CLI_LOGRADOURO` VARCHAR(150) NOT NULL,
  `CLI_BAIRRO` VARCHAR(100) NOT NULL,
  `CLI_CIDADE` VARCHAR(100) NOT NULL,
  `CLI_UF` CHAR(2) NOT NULL,
  `CLI_CEP` CHAR(8) NOT NULL,
  `CLI_SENHA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CLI_CPF`),
  UNIQUE INDEX `CLI_EMAIL_UNIQUE` (`CLI_EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `CLI_CPF_UNIQUE` (`CLI_CPF` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `restaurantes_db`.`PRATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`PRATOS` (
  `PRA_COD` INT NOT NULL,
  `PRA_NOME` VARCHAR(100) NOT NULL,
  `PRA_PRECO` DECIMAL(10,2) NOT NULL,
  `TIP_PRA_COD` INT NOT NULL,
  PRIMARY KEY (`PRA_COD`),
  INDEX `FK_PRA_TIPPRA` (`TIP_PRA_COD` ASC) VISIBLE,
  CONSTRAINT `FK_PRA_TIPPRA`
    FOREIGN KEY (`TIP_PRA_COD`)
    REFERENCES `restaurantes_db`.`TIPO_PRATO` (`TIP_PRA_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`RESTAURANTE_TIPO_PRATO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`RESTAURANTE_TIPO_PRATO` (
  `RES_CNPJ` CHAR(14) NOT NULL,
  `TIP_PRA_COD` INT NOT NULL,
  PRIMARY KEY (`RES_CNPJ`, `TIP_PRA_COD`),
  INDEX `FK_RTP_TIPPRA` (`TIP_PRA_COD` ASC) VISIBLE,
  CONSTRAINT `FK_RTP_RES`
    FOREIGN KEY (`RES_CNPJ`)
    REFERENCES `restaurantes_db`.`RESTAURANTES` (`RES_CNPJ`),
  CONSTRAINT `FK_RTP_TIPPRA`
    FOREIGN KEY (`TIP_PRA_COD`)
    REFERENCES `restaurantes_db`.`TIPO_PRATO` (`TIP_PRA_COD`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`PEDIDOS` (
  `PED_COD` INT NULL DEFAULT NULL,
  `PED_STATUS` VARCHAR(50) NOT NULL,
  `PED_DATA` DATE NOT NULL,
  `PED_PRECO` DECIMAL(10,2) NOT NULL,
  `CLI_CPF` CHAR(11) NOT NULL,
  `FOR_PAG_COD` INT NOT NULL,
  `RET_COD` INT NOT NULL,
  `RES_CNPJ` CHAR(14) NOT NULL,
  PRIMARY KEY (`PED_COD`),
  INDEX `FK_PED_CLI` (`CLI_CPF` ASC) VISIBLE,
  INDEX `FK_PED_FORPAG` (`FOR_PAG_COD` ASC) VISIBLE,
  INDEX `FK_PED_RET` (`RET_COD` ASC) VISIBLE,
  INDEX `FK_PED_RES` (`RES_CNPJ` ASC) VISIBLE,
  CONSTRAINT `FK_PED_CLI`
    FOREIGN KEY (`CLI_CPF`)
    REFERENCES `restaurantes_db`.`CLIENTES` (`CLI_CPF`),
  CONSTRAINT `FK_PED_FORPAG`
    FOREIGN KEY (`FOR_PAG_COD`)
    REFERENCES `restaurantes_db`.`FORMA_PAG` (`FOR_PAG_COD`),
  CONSTRAINT `FK_PED_RET`
    FOREIGN KEY (`RET_COD`)
    REFERENCES `restaurantes_db`.`RETIRADA` (`RET_COD`),
  CONSTRAINT `FK_PED_RES`
    FOREIGN KEY (`RES_CNPJ`)
    REFERENCES `restaurantes_db`.`RESTAURANTES` (`RES_CNPJ`));


-- -----------------------------------------------------
-- Table `restaurantes_db`.`ITEM_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurantes_db`.`ITEM_PEDIDO` (
  `PED_COD` INT NULL DEFAULT NULL,
  `PRA_COD` INT NULL DEFAULT NULL,
  `ITE_QUANTIDADE` INT NOT NULL,
  PRIMARY KEY (`PED_COD`, `PRA_COD`),
  INDEX `FK_ITEM_PRA` (`PRA_COD` ASC) VISIBLE,
  CONSTRAINT `FK_ITEM_PED`
    FOREIGN KEY (`PED_COD`)
    REFERENCES `restaurantes_db`.`PEDIDOS` (`PED_COD`),
  CONSTRAINT `FK_ITEM_PRA`
    FOREIGN KEY (`PRA_COD`)
    REFERENCES `restaurantes_db`.`PRATOS` (`PRA_COD`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
